// Generated by CoffeeScript 1.8.0
var a;

a = {
  params: function() {
    return {
      type: 'hash',
      optional_keys: {
        filter: {
          type: 'hash',
          any_key: true
        },
        sort: {
          type: 'array',
          value: {
            type: 'hash',
            keys: {
              by: 'string',
              order: 'string'
            }
          }
        },
        page: {
          type: 'hash',
          keys: {
            num: 'int',
            size: 'int'
          }
        }
      }
    };
  },
  retval: function() {
    return {
      type: 'collection',
      value: {
        type: 'hash',
        keys: {
          id: 'int',
          name: 'string'
        }
      }
    };
  }
};
