// Generated by CoffeeScript 1.8.0
var promise;

promise = require('../../promise');

module.exports = {
  name: 'Databases',
  init: function() {},
  methods: {
    fetch: {
      func: function(params) {
        return 111;
      }
    },
    add: {
      func: function(fields) {
        throw new Error('1');
      }
    },
    updateByPk: {
      func: function(pk, fields) {}
    },
    deleteByPk: {
      func: function(pk) {}
    }
  },
  childs: {
    tables: require('./tables')
  }
};
