// Generated by CoffeeScript 1.8.0
module.exports = {
  name: 'Databases',
  init: function() {},
  methods: {
    fetch: {
      func: function(params) {}
    },
    add: {
      func: function(fields) {}
    },
    updateByPk: {
      func: function(pk, fields) {}
    },
    deleteByPk: {
      func: function(pk) {}
    }
  },
  childs: {
    tables: require('./tables')
  }
};
