// Generated by CoffeeScript 1.8.0
module.exports = {
  params: {
    host: 'string',
    user: 'string',
    password: 'password'
  },
  init: function() {},
  schema: {
    databases: require('./databases')
  }
};
