// Generated by CoffeeScript 1.8.0
var mysql;

mysql = require('mysql');

module.exports = {
  params: {
    host: 'string',
    user: 'string',
    password: 'password'
  },
  init: function() {
    return console.log(777, this);
  },
  schema: {
    databases: require('./databases')
  }
};
