// Generated by CoffeeScript 1.8.0
module.exports = {
  name: 'Table rows',
  methods: {
    fetch: {
      func: function() {
        return 1;
      }
    }
  },
  init: function() {
    return console.log(555, this, arguments);
  }
};
