// Generated by CoffeeScript 1.8.0
var Collection;

Collection = (function() {
  function Collection(driver, schema, _arg) {
    this.driver = driver;
    this.schema = schema;
    this.url = _arg.url, this.urlArr = _arg.urlArr;
    this.Self = {};
  }

  Collection.prototype.execMethod = function(methodName, args) {};

  Collection.prototype.getStructure = function() {};

  return Collection;

})();

module.exports = Collection;
