// Generated by CoffeeScript 1.8.0
var Driver;

Driver = (function() {
  function Driver(driverObject, params) {
    this._collections = {};
  }

  Driver.prototype.getCollection = function(collUrl) {};

  return Driver;

})();

module.exports = Driver;
